package com.tosak.authos.duster

import com.github.ajalt.clikt.command.SuspendingCliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import io.ktor.client.*
import io.ktor.client.engine.apache5.Apache5
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.plugins.logging.*
import io.ktor.serialization.jackson.*
import java.io.File
import java.util.Properties


val client = HttpClient(Apache5) {
    install(ContentNegotiation) {
        jackson()
    }
    install(Logging) {
        logger = Logger.DEFAULT
        level = LogLevel.INFO
    }
    expectSuccess = true
}

object DusterConfig {
    var dusterBaseUrl: String = "http://localhost:8785"
    var authosBaseUrl: String = "http://localhost:8080"

    fun init() {
        val configFile = File("${System.getProperty("user.home")}/.dstr/dstr.config")
        if (configFile.exists()) {
            val props = Properties()
            configFile.inputStream().use { props.load(it) }
            props.getProperty("duster_base_url")?.let { dusterBaseUrl = it }
            props.getProperty("authos_base_url")?.let { authosBaseUrl = it }
        }
        System.getenv("DUSTER_BASE_URL")?.let { dusterBaseUrl = it }
        System.getenv("AUTHOS_BASE_URL")?.let { authosBaseUrl = it }
    }
}

class DusterCli : SuspendingCliktCommand(name = "dstr") {
    val host by option(
        "--host",
        help = "Duster base URL. Overrides DUSTER_BASE_URL env var and ~/.dstr/dstr.config"
    ).default("")

    val authosHost by option(
        "--authos-host",
        help = "Authos base URL. Overrides AUTHOS_BASE_URL env var and ~/.dstr/dstr.config"
    ).default("")

    override fun help(context: Context) = "DSTR - CLI tool for your Duster Client"
    override fun helpEpilog(context: Context) = """
        - Add client credentials generated by Authos by running:${""}
        dstr credentials save -cid <your_client_id> -cs <your_client_secret>

        - Configure server URL persistently via ~/.dstr/dstr.config:${""}
        duster_base_url=http://myduster.example.com${""}
        authos_base_url=http://myauthos.example.com
    """.trimIndent()

    override suspend fun run() {
        DusterConfig.init()
        if (host.isNotBlank()) DusterConfig.dusterBaseUrl = host
        if (authosHost.isNotBlank()) DusterConfig.authosBaseUrl = authosHost
    }
}
