apiVersion: v1
kind: Service
metadata:
  name: duster-client
  labels:
    app: duster-client
spec:
  type: ClusterIP
  selector:
    app: duster-client
  ports:
    - name: http
      protocol: TCP
      port: 8785
      targetPort: http
